name: php-cs-fixer

on:
  push:
    branches: [ v2.0 ]
  pull_request:
    branches: [ v2.0 ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install

      - name: PHPCSFixer check
        run: composer pint

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling